import { sql } from 'drizzle-orm';
import { customType, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Primary key: a UUID v7 (time-sortable, so new rows land at the end of the index),
 * generated by the database with uuid_generate_v7() from migration 0001. Rows inserted
 * by plain SQL or CSV imports get one too.
 */
export const id = () =>
  uuid()
    .primaryKey()
    .default(sql`uuid_generate_v7()`);

/**
 * created_at / updated_at. `updatedAt` is refreshed by Drizzle on every update made
 * through the query builder (raw SQL updates must set it themselves).
 */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

export interface LngLat {
  lng: number;
  lat: number;
}

/**
 * Parses the hex EWKB that Postgres returns for a geography point.
 * Layout: byte order (1 byte), type (uint32, 0x20000000 flags an SRID), SRID (uint32), x, y (float64).
 */
export function parsePointEwkb(hex: string): LngLat {
  const bytes = Buffer.from(hex, 'hex');
  const littleEndian = bytes.readUInt8(0) === 1;
  const readUInt32 = (offset: number) =>
    littleEndian ? bytes.readUInt32LE(offset) : bytes.readUInt32BE(offset);
  const readDouble = (offset: number) =>
    littleEndian ? bytes.readDoubleLE(offset) : bytes.readDoubleBE(offset);

  const type = readUInt32(1);
  if ((type & 0xffff) !== 1) {
    throw new Error(`Expected a point, got geometry type ${String(type & 0xffff)}`);
  }
  const offset = type & 0x20000000 ? 9 : 5;
  return { lng: readDouble(offset), lat: readDouble(offset + 8) };
}

/**
 * A PostGIS `geography(Point, 4326)` column, read and written as `{ lng, lat }`.
 * geography (not geometry) so distances and radii are in meters on the real Earth.
 */
export const geographyPoint = customType<{ data: LngLat; driverData: string }>({
  dataType: () => 'geography(Point, 4326)',
  // EWKT: longitude first, then latitude.
  toDriver: ({ lng, lat }) => `SRID=4326;POINT(${String(lng)} ${String(lat)})`,
  fromDriver: parsePointEwkb,
});
