import { openApiDocument } from '@paw/api/openapi';
import openapiTS, { astToString, type OpenAPI3 } from 'openapi-typescript';

const HEADER = `// Generated by \`pnpm api:generate\` from the API's route schemas. Do not edit.\n\n`;

export const OPENAPI_FILE = new URL('../openapi.json', import.meta.url);
export const SCHEMA_FILE = new URL('./schema.ts', import.meta.url);

/** Contents of openapi.json (the API contract) and schema.ts (its TypeScript types). */
export async function generateClientFiles(): Promise<{ openapi: string; schema: string }> {
  const document = await openApiDocument();
  // @fastify/swagger returns a loosely typed object; it is an OpenAPI 3 document.
  const ast = await openapiTS(document as unknown as OpenAPI3);
  return {
    openapi: `${JSON.stringify(document, null, 2)}\n`,
    schema: HEADER + astToString(ast),
  };
}
